@import gg.jte.Content
@param Content content

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Hexlet Javalin Example</title>
    <link rel="stylesheet" href="/application.css">
</head>
<body>
<header>
    <a href="/">Home</a>
</header>
${content}
<footer>
    <a href="https://github.com/NikitaOguz">My Github</a>
</footer>
</body>
</html>